#!/bin/sh
# This file only makes sense if you have the annotator repository cloned
# to the same directory where you keep dom-text-mapper.

cd "$(dirname "$0")"
rm -rf ../src/.annotator-map
mkdir -p ../src/.annotator-map
watch -n1 "for i in ../src/*.map;do sed \$i -e \"s/\.\./\./\" > ../src/.annotator-map/\`basename \$i\`;done; cp -u -t ../../annotator/lib/vendor ../src/*.js ../src/.annotator-map/*.map; cp -u -t ../../annotator/lib/vendor/src ../src/*.coffee; cp -u ../lib/mutation-summary/*.js ../../annotator/lib/vendor/"
